### ISSUE TITLE
Meteor.isProduction is true in unit tests on 2.13.1

### ISSUE THREAD

**Issue by ToyboxZach** [meteor/meteor#12769]
I have this in my server code:
`console.info("METEOR IS PRODUCTION", Meteor.isProduction)`
And in my unit test its returning true

This is only happening on my linux circleCi and not locally on my macbook. 

I don't have any idea why this would break so I don't know how to dive into this more if anyone has good ideas.

This is the test command I am running:
`TEST_BROWSER_DRIVER=puppeteer meteor test --driver-package meteortesting:mocha --port 3050 --once --exclude-archs web.browser.legacy`

And it has been working on 2.13 for a while so this is a new issue.

This is my circle ci setup:
```
executors:
  main-tests:
    docker:
      - image: cimg/node:14.21.3-browsers
    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx2048m"
      # These, mostly overlapping, flags ensure that CircleCI is as pretty as
      # possible for a non-interactive environment.  See also: --headless.
      METEOR_HEADLESS: true
      METEOR_PRETTY_OUTPUT: 0

      # In an effort to stop SIGSEGV, this just doesn't bother cleaning up
      # the mess of temp directories that Meteor makes.
      METEOR_SAVE_TMPDIRS: 1

      # These will be evaled before each command.
      PRE_TEST_COMMANDS: |-
        ulimit -c unlimited; # Set core dump size as Ubuntu 14.04 lacks prlimit.
        ulimit -a # Display all ulimit settings for transparency.
      LANG: C.UTF-8
      LANGUAGE: C.UTF-8
      LC_ALL: C.UTF-8
      LC_NUMERIC: en_US.UTF-8
      METEOR_BIN_TMP_DIR: /home/circleci/build-temp/
      METEOR_BIN_TMP_FILE: meteor-bin-temp
    working_directory: ~/app
```
    
Further information:
On the server process.env.NODE_ENV is set to 'production', but NODE_ENV is not set from the circle ci context. So it is being set somewhere within Meteor incorrectly
