### ISSUE TITLE
meteor errors on multiple comments in one CSS declaration block

### ISSUE THREAD

**Issue by thosmos** [meteor/meteor#2334]
**See reproduction [here](https://github.com/hwillson/meteor-issue-2334)**

----

When I bring in a new Jquery Mobile CSS theme from ThemeRoller I need to remove CSS comments in order for meteor release 0.8.2 to be happy.  Here's the error:

```
=> Started proxy.
=> Started MongoDB.     
=> Errors prevented startup:

While building the application:
client/jqm.theme.min.css: property missing ':' near line 91:44

=> Your application has errors. Waiting for file change.
```

Here's the unmodified CSS:

``` CSS
.ui-corner-all {
    -webkit-border-radius: .6em /*{global-radii-blocks}*/;
    border-radius: .6em /*{global-radii-blocks}*/;
}
```

And the modification to make meteor happy:

``` CSS
.ui-corner-all {
    -webkit-border-radius: .6em /*{global-radii-blocks}*/;
    border-radius: .6em;
}
```
