### ISSUE TITLE
import less files in packages doesn't work

### ISSUE THREAD

**Issue by frozeman** [meteor/meteor#5242]
Since 1.2 my packages less files aren't imported anymore.
 I have a package with the following files:
```
- main.less // imports elements.less
- elements.less
```

In `main.less` i tried everything:
```less
import 'elements.less';
import './elements.less';
import 'my:package/elements.less';
import 'my_package/elements.less';
import 'my-package/elements.less';
import '{my:package}/elements.less';
```

But i always get:
```
   While processing files with less (for target web.browser):
   packages/ethereum:elements/main.less:3: Unknown import: elements.less
```

I also tried already `api.addAssets()` to add the files before, but didn't help.

If i use `api.addFiles` to add all less files, it doesn't import the variables or mixing of the other less files to the following ones:
```js
  api.addFiles('lib/lesshat.less', 'client');
  api.addFiles('containers.less', 'client');
  api.addFiles('elements.less', 'client');
  api.addFiles('main.less', 'client');
```

I then get errors like:
```
   While processing files with less (for target web.browser):
   packages/ethereum:elements/containers.less:10:12: No matching definition was found for `.blur(4px)`
   packages/ethereum:elements/elements.less:37:17: variable @colorGray is undefined
   packages/ethereum:elements/main.less:3: Unknown import: {ethereum-elements}/elements.less
   client/styles/main.less:2: Unknown import: public/dapp-styles/dapp-styles.less
```

How do i do it right and where can if find proper docs?
