### ISSUE TITLE
less package strips absolute paths

### ISSUE THREAD

**Issue by edemaine** [meteor/meteor#8209]
Example file `test.less`:

```less
@font-folder: "/fonts";
@font-face { src: url('@{font-folder}/test.eot'); }
```

Output from `lessc` or `lessc -ru`:

```css
@font-face {
  src: url('/fonts/test.eot');
}
```

Output in `.meteor/local/build/programs/web.browser/merged-stylesheets.css`:

```css
@font-face {
  src: url('fonts/KaTeX_AMS-Regular.eot');
}
```

There seems to be some path magic going on in the `less` package that I couldn't figure out.  Relative URLs like this simply don't work in Meteor when we're trying to refer to static (font) files in the `public` directory.  (Relative paths would depend on the URL of the route being accessed; plus I couldn't even get `../` to be preserved in a font name.)  I could not find any way to get an absolute path emitted in the final CSS.
